import Head from "next/head";
import { TodoPage } from "@/features/todo/page";
import styled from "styled-components";

const Main = styled.main`
  display: flex;
  justify-content: center;
  width: 100%;
  height: 100vh;
  background-color: ${({ theme }) => theme.color.surface2};
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Charcoal-TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <TodoPage />
      </Main>
    </>
  );
}
